### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by gitonio** [bitcoinfibre/bitcoinfibre#15]
Getting compile error in Make. Any help appreciated.

admin@rockpro64:~/bitcoinfibre$ sudo make -j4
Making all in src
make[1]: Entering directory '/home/admin/bitcoinfibre/src'
make[2]: Entering directory '/home/admin/bitcoinfibre/src'
CXX libbitcoinconsensus_la-arith_uint256.lo
CXX libbitcoinconsensus_la-hash.lo
CXX libbitcoinconsensus_la-pubkey.lo
CXX libbitcoinconsensus_la-uint256.lo
CXX libbitcoinconsensus_la-utilstrencodings.lo
make[3]: Entering directory '/home/admin/bitcoinfibre/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
CXX bitcoind-bitcoind.o
CXX libbitcoin_server_a-addrdb.o
gcc gen_context.o -o gen_context
./gen_context
CC src/libsecp256k1_la-secp256k1.lo
CXX libbitcoin_server_a-addrman.o
CCLD libsecp256k1.la
/usr/bin/ar: u' modifier ignored since D' is the default (see `U')
CXX libbitcoin_server_a-bloom.o
make[3]: Leaving directory '/home/admin/bitcoinfibre/src/secp256k1'
CXX libbitcoin_server_a-blockencodings.o
In file included from ./wirehair/cm256.h:32:0,
from ./fec.h:17,
from ./blockencodings.h:8,
from blockencodings.cpp:6:
./wirehair/gf256.h:70:14: fatal error: tmmintrin.h: No such file or directory
#include <tmmintrin.h> // SSSE3: _mm_shuffle_epi8
^~~~~~~~~~~~~
compilation terminated.
Makefile:5653: recipe for target 'libbitcoin_server_a-blockencodings.o' failed
make[2]: *** [libbitcoin_server_a-blockencodings.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/admin/bitcoinfibre/src'
Makefile:9747: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/admin/bitcoinfibre/src'
Makefile:747: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.4.0-1ubuntu118.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu/Linaro 7.4.0-1ubuntu118.04.1)

**Comment by TheBlueMatt** [comment]
You probably have to manually set the appropriate #define in src/wirehair to get it to build on ARM. It otherwise will look for x86 SIMD headers.

**Comment by gitonio** [comment]
Thank you. That worked. Got it to compile on rockpro64.

**Comment by aaron-hanson** [comment]
> Thank you. That worked. Got it to compile on rockpro64.

@gitonio just curious exactly what #define you had to set to get around this?  I'm getting similar compilation errors on my Sempron 145 processor...  It fails when trying to call _mm_shuffle_epi8:
```  CXX      wirehair/libbitcoin_server_a-gf256.o
In file included from wirehair/gf256.h:70:0,
                 from wirehair/gf256.cpp:30:
/usr/lib/gcc/x86_64-linux-gnu/7/include/tmmintrin.h: In function ‘void gf256_mul_mem(void*, const void*, uint8_t, int)’:
/usr/lib/gcc/x86_64-linux-gnu/7/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~~
wirehair/gf256.cpp:1245:16: note: called from here
             h0 = _mm_shuffle_epi8(table_hi_y, h0);
             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
My processor has neither AVX2 nor SSSE3.  For reference here's my cpuinfo:

```processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 6
model name	: AMD Sempron(tm) 145 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 2800.000
cache size	: 1024 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2
bogomips	: 5587.53
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

**Comment by aaron-hanson** [comment]
I ended up getting around this for now by effectively removing the SSSE3 intrinsic calls (I just put some `#if defined(SKIP_THIS)` around the blocks of code in gf256.cpp that check the CpuHasSSSE3 boolean and call _mm_shuffle_epi8).  Is this something that should be moved into a preprocessor directive instead of checking this runtime CpuHasSSSE3 boolean?
