### ISSUE TITLE
Which options have to be specified and how correctly so that the reception via IP / UDP socket works?

### ISSUE THREAD

**Issue by VDelport** [bitcoinfibre/bitcoinfibre#18]
hello, I am working successfully with bitcoinfibre and the option -fecreaddevice. Now I want to use the -addudpnode option, but fail, for example with bitcoind -addudpnode = 127.0.0.1: 5000.
Which options have to be specified and how correctly so that the reception via IP / UDP socket works?

**Comment by TheBlueMatt** [comment]
Maybe specify what you are trying to do more specifically? Why are you trying to connect to another node on localhost?

**Comment by VDelport** [comment]
Thank you for your request,
Yes, I would like to receive the Bitcoin blockchain via Blockstream Satellite. Blockstream Satellite has switched to DVB-S2 since June. Unfortunately I currently have no access to our satellite reception system. That's why I built my own DVB-S2 transmitter and embedded a few Bitcoin blocks in a transport stream. The DVB-S2 transmission works successfully. bitcoinfibre can recognize the blocks with a FIFO and the option -fecreaddevice = input_fifo. But I want to use the options with an IP / UDP socket, and unfortunately it fails. How do you have to set the options?

**Comment by VDelport** [comment]
no answer?

**Comment by TheBlueMatt** [comment]
I have no idea what format the Blockstream Satellite uses on the wire, sadly, but I assume it’s no my FIBRE directly. You should reach out to them and ask.

**Comment by TheBlueMatt** [comment]
Closing as this isn’t about FIBRE, it’s about Blockstream Sat.
