### ISSUE TITLE
What is UDP and TCP ports for bitcoinfibre?

### ISSUE THREAD

**Issue by jeong760** [bitcoinfibre/bitcoinfibre#3]
Dears,

I think I need to open them on my firewall in order to support relay network for my private pool. 
Could you give me a numbers for TCP and UDP?

Thank in advance

**Comment by TheBlueMatt** [comment]
There are no default ports, aside from the default ones for normal Bitcoin Core...
You have to specify the UDP ports used using the -udpport= option as well as the remote ports when you connect/addudpnode.
See http://bitcoinfibre.org/fibre-howto.html and run FIBRE with -? or `bitcoin-cli help | grep udp` for more info on setup and the various options.
