### ISSUE TITLE
Build system do not check for yasm but requires it

### ISSUE THREAD

**Issue by deadalnix** [bitcoinfibre/bitcoinfibre#4]
I was able to autogen/configure without having yasm installed, however, the build fails. It looks like yasm is used but it presence isn't checked.

**Comment by TheBlueMatt** [comment]
Yes, this is true. I dont know much about our build system so neglected bothering to try to add it, patches more than welcome :).

**Comment by TheBlueMatt** [comment]
Addressed on master by https://github.com/bitcoin/bitcoin/pull/10821

**Comment by deadalnix** [comment]
<3 Thanks.
